#ifndef __CONSTANTS_H_
#define __CONSTANTS_H_

#define BITS_PER_CELL 2
#define BITS_PER_LAST_CELL 4

#define MAX_TILE_SIZE 16
#define MIN_TILE_SIZE 8

#define MAX_TILE_DATA_SIZE 574 // (MAX_TILE_SIZE - 1) ^ 2 * BITS_PER_CELL + (MAX_TILE_SIZE ^ 2 - (MAX_TILE_SIZE - 1) ^ 2) * BITS_PER_LAST_CELL
#define MIN_TILE_DATA_SIZE 158 // (MIN_TILE_SIZE - 1) ^ 2 * BITS_PER_CELL + (MIN_TILE_SIZE ^ 2 - (MIN_TILE_SIZE - 1) ^ 2) * BITS_PER_LAST_CELL

#define MAX_TILE_DATA_32 18 // MAX_TILE_DATA_SIZE / BUS_WIDTH
#define MIN_TILE_DATA_32 5 // MIN_TILE_DATA_SIZE / BUS_WIDTH

#define MAX_NUM_DIRECTIONS 256 // MAX_TILE_SIZE * MAX_TILE_SIZE
#define MIN_NUM_DIRECTIONS 64 // MIN_TILE_SIZE * MIN_TILE_SIZE

#define BUS_WIDTH 32
#define BYTES_IN_BUS 4 // BUS_WIDTH / 8
#define DIRECTION_SIZE 4
#define DIRECTIONS_IN_BUS 8 // BUS_WIDTH / DIRECTION_SIZE

#define OPEN_NORTH 0x07 // 0111
#define OPEN_WEST 0x0B  // 1011
#define OPEN_SOUTH 0x0D // 1101
#define OPEN_EAST 0x0E  // 1110

#define NORTH (0xFFFFFFF0 ^ ~OPEN_NORTH) // 1000
#define WEST (0xFFFFFFF0 ^ ~OPEN_WEST)   // 0100
#define SOUTH (0xFFFFFFF0 ^ ~OPEN_SOUTH) // 0010
#define EAST (0xFFFFFFF0 ^ ~OPEN_EAST)   // 0001

#define NORTH_SOUTH (NORTH | SOUTH) // 1010
#define EAST_WEST (EAST | WEST)     // 0101

#endif
